name: pep8_checker
on:
  push:
    paths:
    - '**.k'
  status: {}
jobs:
  pep8_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Display the path and python`s version 
        run: |
          import os
          import sys
          print(sys.version)
          print(os.environ['PATH'])
        shell: python
      - name: Python Style Checker
        run: |
          python -m pip install --upgrade pip
          pip install flake8 numpy matplotlib
      - run: python ./project2/project.py $(find ./project2 -name "*.k")
      - name: Push changes to repo
        run: |
          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add .
          git commit -am "Add new comment"
          git push ${REMOTE}
