name: pep8_checker
on:
  pulls:
    paths:
    - '*.ipynb'
  status: {}
jobs:
  pep8_checker:
    runs-on: ubuntu-latest
    steps:
      - name: import
        run: |
          import numpy as np
	  import matplotlib.pyplot as plt
	  print(np.__version__)	
	shell: python
