name: pep8_checker
on:
  push:
    paths:
    - '*.ipynb'
    - '*.py'
  status: {}
jobs:
  pep8_checker:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: |
          import os
          print(os.environ['PATH'])
        shell: python
      - name: import
        run: |
          import numpy as np
          import matplotlib.pyplot as plt
          print(np.__version__)	
        shell: python
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
