name: pep8_checker
on:
  push:
    paths:
    - '**.py'
  status: {}
jobs:
  pep8_checker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Display the path and python`s version 
        run: |
          import os
          import sys
          print(sys.version)
          print(os.environ['PATH'])
        shell: python
      - name: Python Style Checker
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8
      - name: Python execute
        run: | 
          python3 example.py
